###
GET http://localhost:9999/

###
GET http://localhost:9999/hello

###
GET http://localhost:9999/zlzla

###
GET http://localhost:9999/hello?name=geektutu

# ###
# POST http://localhost:9999/login
# Content-Type: application/json

# {
#     "password": "1234",
#     "username": "geektutu"
# }

###
POST http://localhost:9999/login
Content-Type: application/x-www-form-urlencoded

username=your_username&password=your_password
